"""engines/manimgl/src/utils/audio_sync.py
MaCode AudioSync adapter — ManimGL version.

Reads timeline.csv generated by pipeline/audio-analyze.sh,
provides time query interface for syncing scene animation to music beats.

Usage:
    from utils.audio_sync import AudioSync

    class MyScene(Scene):
        def construct(self):
            sync = AudioSync("assets/bgm_timeline.csv")
            for t in np.arange(0, 10, 1/30):
                feat = sync.at(t)
                intensity = feat["loudness"]
                # drive animation with intensity...
"""

import csv


class AudioSync:
    """Audio beat synchronizer."""

    def __init__(self, csv_path):
        """Load timeline.csv.

        Args:
            csv_path: timeline.csv file path (absolute or relative to scene directory)
        """
        self.data = []
        with open(csv_path, encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                self.data.append({
                    "time": float(row["time"]),
                    "beat": int(row["beat"]),
                    "loudness": float(row["loudness"]),
                    "low": float(row["low"]),
                    "mid": float(row["mid"]),
                    "high": float(row["high"]),
                })
        self.fps = self._infer_fps()

    def _infer_fps(self):
        """Infer frame rate from timestamps."""
        if len(self.data) < 2:
            return 30
        dt = self.data[1]["time"] - self.data[0]["time"]
        return round(1.0 / dt) if dt > 0 else 30

    def _index(self, t):
        """Time -> array index."""
        idx = int(t * self.fps)
        return max(0, min(idx, len(self.data) - 1))

    def at(self, t):
        """Get complete audio features at time t.

        Returns:
            dict: {time, beat, loudness, low, mid, high}
        """
        return dict(self.data[self._index(t)])

    def loudness(self, t):
        """Overall loudness (0.0 ~ 1.0)."""
        return self.data[self._index(t)]["loudness"]

    def low(self, t):
        """Low frequency energy (drums)."""
        return self.data[self._index(t)]["low"]

    def mid(self, t):
        """Mid frequency energy (vocals/instruments)."""
        return self.data[self._index(t)]["mid"]

    def high(self, t):
        """High frequency energy (cymbals/high freq)."""
        return self.data[self._index(t)]["high"]

    def is_beat(self, t):
        """Whether current time falls on a beat."""
        return bool(self.data[self._index(t)]["beat"])

    def beat_time(self, n):
        """Time point of the n-th beat (0-indexed).

        Args:
            n: beat index (0 = first beat)

        Returns:
            float or None: time in seconds, or None if not found
        """
        count = 0
        for row in self.data:
            if row["beat"]:
                if count == n:
                    return row["time"]
                count += 1
        return None

    def beat_count(self):
        """Total number of detected beats."""
        return sum(1 for row in self.data if row["beat"])

    def tempo(self, t, window=1.0):
        """Local tempo multiplier (based on beat density in the last ``window`` seconds).

        Returns:
            float: ~0.5 (slow) ~ 2.0 (fast), used to dynamically adjust animation speed
        """
        t0 = max(0, t - window / 2)
        t1 = t + window / 2
        beats_in_window = sum(
            1 for row in self.data
            if t0 <= row["time"] <= t1 and row["beat"]
        )
        # Assume normal BPM is 120 (2 beats per second), normalize
        expected = window * 2.0
        ratio = (beats_in_window / expected) if expected > 0 else 1.0
        return max(0.5, min(2.0, ratio))
